version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - misspell
    - unconvert
    - unused
    - gosec
    - bodyclose
    - noctx
    - godot
    - goconst
    - gocyclo
    - nestif
    - prealloc
    - gocritic
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - gofumpt
    - goimports
