polling:
  service_url: "https://dikidi.net/550001?p=1.pi-ssm"
  mode: "aggressive"
  service_id_update_rate: 24h
  normal_poll_rate: 1m
  aggressive_poll_rate: 30s
  normal_fetch_rate: 1s
  aggressive_fetch_rate: 500ms

