polling:
  service_url: "https://dikidi.net/550001?p=1.pi-ssm"
  mode: "normal"
  service_id_update_rate: 24h
  normal_poll_rate: 1m30s
  aggressive_poll_rate: 45s
  normal_fetch_rate: 1s
  aggressive_fetch_rate: 500ms
  min_fetch_rate: 10s
  max_fetch_rate: 250ms
  backoff_factor: 2.0
  recovery_factor: 1.2
teacher:
  staring_week: 2
