name: Build for Raspberry PI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.4'

      - name: Install ARM64 cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build for ARM64
        run: |
          export CC=aarch64-linux-gnu-gcc
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 GOARM=8 go build -o mining-bot-arm64 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'mining-bot-arm64'
          path: 'mining-bot-arm64'

