name: Build for Raspberry PI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.4'

      - name: Build for ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -0 mining-bot-arm64 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'mining-bot-arm64'
          path: 'mining-bot-arm64'

